name: Push/Pull File Checker

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check for errors.
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
